// Generates build/web/sw.js: an offline-first service worker that
// precaches the entire app — including every bundled Sefaria text,
// rules, fonts and the self-hosted CanvasKit runtime — so the PWA works
// fully offline after the first visit.
//
//   dart run tool/gen_service_worker.dart [build/web]
//
// The cache name is derived from a hash of every file's contents, so any
// new deployment installs a fresh cache and removes the old one.
import 'dart:convert';
import 'dart:io';

void main(List<String> args) {
  final root = Directory(args.isNotEmpty ? args.first : 'build/web');
  if (!root.existsSync()) {
    stderr.writeln('${root.path} not found — run flutter build web first');
    exit(1);
  }
  const skip = {'sw.js', 'flutter_service_worker.js'};
  final files = <String>[];
  var hash = 0x811c9dc5;
  var bytes = 0;
  for (final f in root.listSync(recursive: true).whereType<File>()) {
    final rel = f.path.substring(root.path.length + 1).replaceAll('\\', '/');
    if (skip.contains(rel) || rel.endsWith('.map') || rel.endsWith('.symbols')) continue;
    // Only one CanvasKit build is needed offline besides the default;
    // skwasm variants are for --wasm builds, which this app doesn't use.
    if (rel.startsWith('canvaskit/') && (rel.contains('skwasm') || rel.contains('wimp'))) continue;
    files.add(rel);
    final data = f.readAsBytesSync();
    bytes += data.length;
    for (final b in utf8.encode(rel)) {
      hash = ((hash ^ b) * 0x01000193) & 0xffffffff;
    }
    for (var i = 0; i < data.length; i += 997) {
      hash = ((hash ^ data[i]) * 0x01000193) & 0xffffffff;
    }
    hash = ((hash ^ data.length) * 0x01000193) & 0xffffffff;
  }
  files.sort();
  // CanvasKit ships a Chromium-optimized build and a generic one; each
  // browser only loads one, so precache just the matching variant.
  final chromium = files.where((f) => f.startsWith('canvaskit/chromium/')).toList();
  final generic = files.where((f) => f.startsWith('canvaskit/') && !f.startsWith('canvaskit/chromium/')).toList();
  // index.html is fetched as "./" by navigations.
  final precache = ['./', ...files.where((f) => !f.startsWith('canvaskit/'))];
  final version = hash.toRadixString(16).padLeft(8, '0');

  final sw = '''
// GENERATED by tool/gen_service_worker.dart — do not edit.
// Precaches the app shell, every Sefaria text/rule/font and one CanvasKit build.
const CACHE = 'amud-$version';
const RUNTIME = 'amud-runtime';
const PRECACHE = ${const JsonEncoder.withIndent('  ').convert(precache)};
const CANVASKIT_CHROMIUM = ${jsonEncode(chromium)};
const CANVASKIT_GENERIC = ${jsonEncode(generic)};

// Mirrors Flutter's loader: Chromium browsers use the Chromium build.
function canvaskitFiles() {
  const brands = (self.navigator.userAgentData && self.navigator.userAgentData.brands) || [];
  const isChromium = brands.some((b) => b.brand === 'Chromium');
  return isChromium ? CANVASKIT_CHROMIUM : CANVASKIT_GENERIC;
}

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // Fetch in small batches so a slow connection isn't overwhelmed.
    const all = PRECACHE.concat(canvaskitFiles());
    for (let i = 0; i < all.length; i += 8) {
      await cache.addAll(all.slice(i, i + 8).map((u) => new Request(u, {cache: 'reload'})));
    }
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (key !== CACHE && key !== RUNTIME && !key.startsWith('amud-voice-')) await caches.delete(key);
    }
    // Same-origin files cached at runtime belong to the old deployment.
    const runtime = await caches.open(RUNTIME);
    for (const req of await runtime.keys()) {
      if (new URL(req.url).origin === location.origin) await runtime.delete(req);
    }
    await self.clients.claim();
  })());
});

self.addEventListener('message', (event) => {
  if (event.data === 'skipWaiting') self.skipWaiting();
});

// Push is delivered by the optional VAPID server while the app is closed.
self.addEventListener('push', (event) => {
  event.waitUntil((async () => {
    let data;
    try { data = event.data.json(); } catch (_) { return; }
    const route = typeof data.route === 'string' && data.route.startsWith('/') && !data.route.startsWith('//') ? data.route : '/zmanim';
    await self.registration.showNotification(String(data.title || 'Amud'), {
      body: String(data.body || ''), icon: 'icons/Icon-192.png', tag: 'amud-' + data.id, data: route,
    });
  })());
});

// Tapping a notification focuses the open app (or opens it) on the page it
// is about (Zmanim for zman alerts).
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  event.waitUntil((async () => {
    const all = await self.clients.matchAll({type: 'window', includeUncontrolled: true});
    for (const c of all) {
      if ('focus' in c) {
        c.postMessage({type: 'notification-tap', route: event.notification.data || '/zmanim'});
        return c.focus();
      }
    }
    return self.clients.openWindow('./#' + (event.notification.data || '/zmanim'));
  })());
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);

  if (url.pathname.includes('/api/')) return;

  // App shell: serve cached index.html for navigations (offline-first),
  // refreshing it in the background.
  if (req.mode === 'navigate' && url.origin === location.origin) {
    event.respondWith((async () => {
      const cache = await caches.open(CACHE);
      const cached = await cache.match('./');
      const network = fetch(req).then((res) => {
        if (res.ok) cache.put('./', res.clone());
        return res;
      }).catch(() => undefined);
      return cached || (await network) || Response.error();
    })());
    return;
  }

  // Same-origin assets: cache-first (they're content-versioned by CACHE).
  if (url.origin === location.origin) {
    event.respondWith((async () => {
      // This deployment's precache first, so nothing stale can shadow it.
      const hit = (await (await caches.open(CACHE)).match(req, {ignoreSearch: true})) ||
          (await (await caches.open(RUNTIME)).match(req, {ignoreSearch: true}));
      if (hit) return hit;
      const res = await fetch(req);
      if (res.ok) (await caches.open(RUNTIME)).put(req, res.clone());
      return res;
    })());
    return;
  }

  // Fallback glyph fonts Flutter may request from Google Fonts (emoji,
  // rare scripts), and the Firebase Analytics scripts (versioned URLs):
  // cache them the first time so they load offline later.
  if (url.hostname === 'fonts.gstatic.com' || url.hostname === 'fonts.googleapis.com' ||
      (url.hostname === 'www.gstatic.com' && url.pathname.startsWith('/firebasejs/'))) {
    event.respondWith((async () => {
      const cache = await caches.open(RUNTIME);
      const hit = await cache.match(req);
      if (hit) return hit;
      const res = await fetch(req);
      if (res.ok || res.type === 'opaque') cache.put(req, res.clone());
      return res;
    })());
  }
});
''';
  File('${root.path}/sw.js').writeAsStringSync(sw);
  stdout.writeln('sw.js: ${files.length} files, ${(bytes / 1048576).toStringAsFixed(1)} MB, cache amud-$version');
}
