#!/usr/bin/env python3
"""Generates lib/src/data/aliyot.g.dart from @hebcal/leyning's aliyot.json.

Usage: gen_aliyot.py <path to hebcal-leyning/src/aliyot.json>
"""
import json, os, sys

OUT = os.path.join(os.path.dirname(__file__), '..', 'lib', 'src', 'data', 'aliyot.g.dart')


def dstr(s):
    return "'" + s.replace('\\', '\\\\').replace("'", "\\'") + "'"


data = json.load(open(sys.argv[1], encoding='utf-8'))
lines = []
for name, p in data.items():
    k = p['fullkriyah']
    aliyot = ', '.join(f'({dstr(k[n][0])}, {dstr(k[n][1])})' for n in '1234567')
    lines.append(f'  {dstr(name)}: ({p["book"]}, [{aliyot}]),')

with open(OUT, 'w', encoding='utf-8') as f:
    f.write('// GENERATED by tool/gen_aliyot.py from @hebcal/leyning (BSD-2-Clause). DO NOT EDIT.\n')
    f.write('// ignore_for_file: lines_longer_than_80_chars\n\n')
    f.write('/// Shabbat aliyot (full kriyah) by parsha, doubled parshiyot as "X-Y":\n')
    f.write('/// the book (1 = Bereshit) and seven (begin, end) "chapter:verse" ranges.\n')
    f.write('const Map<String, (int, List<(String, String)>)> parshaAliyotData = {\n')
    f.write('\n'.join(lines) + '\n};\n')
print('ok')
